### ISSUE TITLE
Fatal error $this->clockwork is not present in RequestFilter::postRequest()

### ISSUE THREAD

**Issue by axyr** [markguinn/silverstripe-clockwork#4]
With Silverstripe 3.1.12 I get this error? : 

PHP Fatal error:  Call to a member function getRequest() on a non-object in /clockwork/src/RequestFilter.php on line 63

**Comment by axyr** [comment]
Not sure if this is good practice, but it seems to work...

changing protected $clockwork; to protected static $clockwork;

http://sspaste.com/paste/show/5511b1afde02f

**Comment by markguinn** [comment]
I think this was actually fixed in PR #5.
