### ISSUE TITLE
Issues with SS 3.2

### ISSUE THREAD

**Issue by mi3ll** [markguinn/silverstripe-clockwork#6]
Probably due to the database overhaul in SS 3.2, clockwork is not working anymore...

One of the errors I am getting:

```
Fatal error: Declaration of Clockwork\Support\Silverstripe\DatabaseProxy::comparisonClause() must be compatible with SS_Database::comparisonClause($field, $value, $exact = false, $negate = false, $caseSensitive = NULL, $parameterised = false) in /home/vagrant/code/milkyway-multimedia/***.com/clockwork/src/DatabaseProxy.php on line 17
```

**Comment by markguinn** [comment]
Thanks for the heads up. If you submit a PR I'll merge it ASAP. If not, we've got a new SS3.2 project kicking off in the next 2-3 weeks that will hit this bug and I'll be fixing it then if not before.

**Comment by mi3ll** [comment]
Sorry, a bit of a lazy fix but it works...

**Comment by markguinn** [comment]
In what sense is it lazy? It looks fine to me but I also haven't spent much time looking at the DB code in 3.2 vs 3.1.

I need to give a bit of thought to how to make this still work with 3.1 but I'll try to get this merged today. Thank you.

**Comment by mi3ll** [comment]
Haha I guess lazy is the wrong word... I was commenting on not making it backwards compatible. And it feels like it should be injected in?

I think simply tagging two new versions and changing the require: silverstripe/framework for each of them should do it (stolen from the sqlite module)?

## 0.1
require: "silverstripe/framework": ">=3.0,<3.2"

## 0.2
require: "silverstripe/framework": "~4.0"

**Comment by jonom** [comment]
@markguinn don't mean to pressure you but I'm looking forward to having Clockwork in my toolkit again :D

**Comment by jonom** [comment]
Have tested this quickly and seems to work for me on 3.2. FYI for anyone interested you can test/use this dev branch by putting this in your composer.json
```yml
{
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/mi3ll/silverstripe-clockwork.git"
		}
	],
	"require": {
		"markguinn/silverstripe-clockwork": "dev-patch-3.2 as 1.0"
	}
}
```
