### ISSUE TITLE
Controller timeline logging not working

### ISSUE THREAD

**Issue by jonom** [markguinn/silverstripe-clockwork#8]
This test in ClockworkControllerExtension is failing: `class_exists('Clockwork\\Request\\ClockworkTimeline')`.

Easy fix though, just needs to be changed to `class_exists('Clockwork\\Request\\Timeline')`.

Let me know if you want a PR for this.

**Comment by markguinn** [comment]
That'd be great. Thanks!

**Comment by markguinn** [comment]
Nevermind. I just took care of it. Thanks for catching this!

**Comment by jonom** [comment]
:+1: Cheers
